export const ACTIONS = {
  SET_SERVICES: 'SET_SERVICES',
  SET_SERVICE_DATA: 'SET_SERVICE_DATA',
  SET_SERVICE_CONFIG: 'SET_SERVICE_CONFIG',
  REMOVE_SERVICE: 'REMOVE_SERVICE',
  SET_TEMP_CONFIG: 'SET_TEMP_CONFIG',
  SET_LAYOUTS: 'SET_LAYOUTS'
}
